
// Autogenerated file, do not edit.

int dwFileVersion[4] = { 1,0,60,68 };
int dwProductVersion[4] = { 1,0,60,68 };

const char *pszFileVersion = "1.0.60.68";
const char *pszProductVersion = "1.0.60.68";
