
// Autogenerated file, do not edit.

int dwFileVersion[4] = { 1,0,58,139 };
int dwProductVersion[4] = { 1,0,58,139 };

const char *pszFileVersion = "1.0.58.139";
const char *pszProductVersion = "1.0.58.139";
