
// Autogenerated file, do not edit.

int dwFileVersion[4] = { 1,0,59,1 };
int dwProductVersion[4] = { 1,0,59,1 };

const char *pszFileVersion = "1.0.59.1";
const char *pszProductVersion = "1.0.59.1";
